[package]
name = "ripple-carry-adder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
full-adder = {path = "../full-adder"}
pcb-rs = {path="../../pcb-rs/pcb-rs"}