[package]
name = "ring-counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic-gates = {path ="../basic-gates"}
pcb-rs = {path="../../pcb-rs/crates/pcb-rs"}
latches = {path="../latches"}
